### ISSUE TITLE
KeyError: 'DATABASE_URL' (maybe a 0.4.2 regression?)

### ISSUE THREAD

**Issue by kti-matt** [joke2k/django-environ#117]
Thanks for your work on django-environ.

My project works fine with 0.4.1, but breaks in 0.4.2, released this morning.

I'm using Python 3.4.2 on Debian 8 and Django 1.10 in a virtualenv. I checked in a couple of ways that yes, my DATABASE_URL variable was being loaded properly. In particular, I added a line in my settings file, `print(os.environ['DATABASE_URL'])`, immediately prior to my `env.db()` call, and it printed my setting as I expected.

If this is not a regression, then perhaps some upgrade docs would be in order so I know what I need to change in my project to use the latest django-environ.

Thanks!

```
(env3) ipmetadataretention@host:~$ manage.py shell
Traceback (most recent call last):
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/environ/environ.py", line 265, in get_value
    value = self.ENVIRON[var]
KeyError: 'DATABASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/core/management/base.py", line 348, in execute
    saved_locale = translation.get_language()
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/utils/translation/__init__.py", line 190, in get_language
    return _trans.get_language()
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/share/ip-metadata-retention/django/ipmetadataretention/settings/production.py", line 2, in <module>
    from .common import *  # noqa: F401, F403
  File "/usr/share/ip-metadata-retention/django/ipmetadataretention/settings/common.py", line 87, in <module>
    'default': env.db(),
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/environ/environ.py", line 196, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/environ/environ.py", line 269, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/environ/environ.py", line 265, in get_value
    value = self.ENVIRON[var]
KeyError: 'DATABASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ip-metadata-retention/django/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/core/management/base.py", line 317, in run_from_argv
    connections.close_all()
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/db/utils.py", line 229, in close_all
    for alias in self:
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/db/utils.py", line 223, in __iter__
    return iter(self.databases)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/db/utils.py", line 156, in databases
    self._databases = settings.DATABASES
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/share/ip-metadata-retention/django/ipmetadataretention/settings/production.py", line 2, in <module>
    from .common import *  # noqa: F401, F403
  File "/usr/share/ip-metadata-retention/django/ipmetadataretention/settings/common.py", line 87, in <module>
    'default': env.db(),
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/environ/environ.py", line 196, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "/var/lib/ipmetadataretention/env3/lib/python3.4/site-packages/environ/environ.py", line 269, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable
```

**Comment by QasimK** [comment]
Regression with #105. Environment variables are now only stored within the class when `read_env` is called, which not everyone may do. Further, **unconfirmed**, sub-processes do not get an updated `os.environ` as a copy of it is made (not sure what the effect of `os.environ.copy()` is exactly).

@max-arnold @joke2k 

Due to [the design of django-environ outlined](https://github.com/joke2k/django-environ/issues/58#issuecomment-268228548) and #66, I do not immediately see a way to fix #58 which:

1. Prioritises "passed-in" environment variables, for example `DEBUG=FALSE ./manage.py runserver` should override `DEBUG=TRUE` in a test.env file.
2. Allows the environment variables in a .env file to override the historical environment variables which become permanently apart of `os.environ` and the environment.
3. (All while keeping the design structure of using one global `os.environ` which `Env` uses, see also #66)

The issue, as I see it, is that we cannot distinguish between environment variables set in `os.environ` by `Env` through reading a file and those that are specified through another way. You want the environment variables specified in the file to always override the environment variables specified by the *previous* file, but not to override the vars specified through the command-line for example.

Assuming a revert on #105. A solution which loses 1 but fixes 2 would be to use `os.environ[key]` instead of `os.environ.setdefault` if and only if `override=True` is specified as a parameter to `read_env`.

**Comment by joke2k** [comment]
I'm looking for a solution, but probably I've to revert on #105.

**Comment by max-arnold** [comment]
It would be nice to have some unit-tests to check cases like (1) and (2)

**Comment by max-arnold** [comment]
@joke2k Do you think adding an option to constructor is the best way to fix this (other than roll back)? I can try to make a patch.

**Comment by riklaunim** [comment]
Affects me as well, 0.4.1 works without problems.

**Comment by joke2k** [comment]
Reverted and released.

I was trying to convert the `Env.ENVIRON` variable into a set of dictionaries, with os.environ as first item as default, in order to allow to use a cascade dicts into `Env.get_value`.

But I postpone this feature for 0.5

If anyone is interested to discuss about that... we can met on freenode#python
