### ISSUE TITLE
AttributeError: 'str' object has no attribute '__root__'

### ISSUE THREAD

**Issue by JimFawkes** [joke2k/django-environ#197]
Hi,

I just got an error that I do not understand. 

**Here is what I did:** 
In order for django-debug-toolbar (dtb) to work I wanted to add 127.0.0.1 to INTERNAL_IPS. Because I was only trying to check if this causes dtb to work, I did not set this setting via environment variables or the env file.
For some reason this throws an exception which has its root in `environ/environ.py", line 730, in __eq__`, because dtb calls `normpath(path)` from `posixpath.py in line 333` (see Traceback below).

I do not understand why django-environ is involved in this at all. Can you give me an explanation?
A nother very strange thing is that any other entry in INTERNAL_IPS does not cause this error.
Why is this specific IP causing this error?

```
Traceback (most recent call last):
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 132, in process_response
    panel.generate_stats(request, response)
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py", line 220, in generate_stats
    'template_dirs': [normpath(x) for x in template_dirs],
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 333, in normpath
    if path == '':
  File "/Users/username/.ENV/my_project/lib/python2.7/site-packages/environ/environ.py", line 730, in __eq__
    return self.__root__ == other.__root__
AttributeError: 'str' object has no attribute '__root__'
```

I apreciate any kind of hint as to how to solve this or how to further debug this or any explanation why this is happening.

**Comment by dennereed** [comment]
I'm experiencing the same issue.  It crops up when I attempt unit tests.

**Comment by gone** [comment]
Also got bit by this - fix was updating settings:
from
`STATIC_ROOT = root("static")`

to

`STATIC_ROOT = root.path("static")
`

**Comment by mlissner** [comment]
This looks like a dup or at least is heavily related to #86
