### ISSUE TITLE
Can't use `default=None` with `env.db()`

### ISSUE THREAD

**Issue by craigds** [joke2k/django-environ#280]
the default value gets passed directly to `urlparse()`:

```python
>>> env.db('TESTVAR', default=None)
Traceback (most recent call last):
  File "<ipython-input-20-5e4c46768a3c>", line 1, in <module>
    env.db('TESTVAR', default=None)
  File "/Users/cdestigter/v/lib/python3.8/site-packages/environ/environ.py", line 204, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "/Users/cdestigter/v/lib/python3.8/site-packages/environ/environ.py", line 381, in db_url_config
    path = unquote_plus(path.split('?', 2)[0])
TypeError: a bytes-like object is required, not 'str'
```

Happy to PR a fix

**Comment by Veilkrand** [comment]
I don't think is a bug

**Comment by craigds** [comment]
agreed, on second thoughts this was a bad idea. I was using this for something that isn't a django db connection, and it was better suited to just using `env.dict()` since the keys ended up not being identical to what django expects
