### ISSUE TITLE
Django, Import "environ" could not be resolved

### ISSUE THREAD

**Issue by Deadlooks** [joke2k/django-environ#370]
`from pathlib import Path

import environ # it is the problem its not importing

env = environ.Env(
    DEBUG = [bool, False]
)

environ.Env.read_env()`

> During handling of the above exception, another exception occurred:
>Traceback (most recent call last):
> File "/home/Django/manage.py", line 22, in <module>
>    main()
>  File "/home/Django/manage.py", line 18, in main
>    execute_from_command_line(sys.argv)
>  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>    utility.execute()
>  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 413, in execute
>    self.fetch_command(subcommand).run_from_argv(self.argv)
>  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 354, in run_from_argv
>    self.execute(*args, **cmd_options)
>  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 61, in execute
>    super().execute(*args, **options)
>  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 398, in execute
>    output = self.handle(*args, **options)
>  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 68, in handle
>    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
>  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 82, in __getattr__
>    self._setup(name)
>  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 69, in _setup
>    self._wrapped = Settings(settings_module)
>  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 170, in __init__
>    mod = importlib.import_module(self.SETTINGS_MODULE)
>  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>  File "/home/Django/settings.py", line 31, in <module>
>    SECRET_KEY = env('SECRET_KEY')
>  File "/home/.local/lib/python3.9/site-packages/environ/environ.py", line 175, in __call__
>    return self.get_value(
>  File "/home/.local/lib/python3.9/site-packages/environ/environ.py", line 371, in get_value
>    raise ImproperlyConfigured(error_msg)
>django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable

### **Please help me to fix it!**

I did pip3 install django-environ

**in terminal when i do python3
import environ
It is importing perfectly but not in django?**

**_Note:_** I am not using any virtual environment,

**Comment by Deadlooks** [comment]
### **Thank you for all who ever visited to this issue!**

i have resolve this issue 

The issue was that i have kept spaces in between the env file showen as bellow

in env file
DEBUG = True
SECRET_KEY = *************

fixed it by 
DEBUG=True
SECRET_KEY=*********
:)
even tho it show pylance error but it just pylance that cannot resolve! as shown in the image
![Screenshot_2022-03-07_02_45_11](https://user-images.githubusercontent.com/91751103/156942861-eb2a65a9-151c-4135-8c71-1d8e7fa47cac.png)
