### ISSUE TITLE
django-stubs doesn't play well with django-environ: raises ImproperlyConfigured: Set the SECRET_KEY environment variable

### ISSUE THREAD

**Issue by sebastian-philipp** [joke2k/django-environ#372]
# x-post to django-stubs: https://github.com/typeddjango/django-stubs/issues/877

```
mypy --config-file ../mypy-django.ini project
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/environ/environ.py", line 367, in get_value
    value = self.ENVIRON[var]
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/environ/fileaware_mapping.py", line 43, in __getitem__
    return self.env[key]
  File "/usr/lib64/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/Repos/src/.tox/mypy/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/sebastian/Repos/src/.tox/mypy/lib64/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/mypy_django_plugin/main.py", line 143, in __init__
    self.django_context = DjangoContext(django_settings_module)
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 95, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 77, in initialize_django
    settings._setup()
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/sebastian/Repos/src/project/project/settings.py", line 33, in <module>
    SECRET_KEY = env('SECRET_KEY')
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/environ/environ.py", line 175, in __call__
    return self.get_value(
  File "/home/sebastian/Repos/src/.tox/mypy/lib/python3.9/site-packages/environ/environ.py", line 371, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable
ERROR: InvocationError for command /home/sebastian/Repos/src/.tox/mypy/bin/mypy --config-file ../mypy-django.ini project (exited with code 1)
```

I get the approach of the django-stubs mypy plugin to execute the `settings.py` and I like the approach of django-environ to read settings from the environment. 

How can we combine both? 

My workaround right now looks like so:

```
if 'mypy_django_plugin' in sys.modules:
    # https://github.com/joke2k/django-environ/issues/372
    env = environ.Env(
        SECRET_KEY=(str, 'django-insecure'),
        DEBUG=(bool, False),
        DATABASE_URL=(str, 'sqlite:///sqlite.db'),
    )
else:
    env = ...
```

**Comment by sergeyklay** [comment]
As far as I can tell, this issue is related to typeddjango/django-stubs. I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks
