### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by edmorley** [joke2k/django-environ#44]
Using current PyPI django-environ release (v0.3.0):
```bash
>>> import environ
>>> env = environ.Env()
>>> env.url("FOO", default=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/environ/environ.py", line 173, in url
    return self.get_value(var, cast=urlparse.urlparse, default=default, parse_default=True)
  File "/usr/lib/python2.7/site-packages/environ/environ.py", line 260, in get_value
    value = self.parse_value(value, cast)
  File "/usr/lib/python2.7/site-packages/environ/environ.py", line 308, in parse_value
    value = cast(value)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```

Expected:
It returns `None` like `env("BAR", default=None)` would.

**Comment by edmorley** [comment]
Thank you :-)
