### ISSUE TITLE
DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead on 3.12

### ISSUE THREAD

**Issue by graingert-coef** [joke2k/django-environ#524]
```
python -Werror -c 'import environ'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/thomas/.virtualenvs/blueprint-app/lib/python3.12/site-packages/environ/__init__.py", line 30, in <module>
    from .environ import *
  File "/Users/thomas/.virtualenvs/blueprint-app/lib/python3.12/site-packages/environ/environ.py", line 29, in <module>
    from .compat import (
  File "/Users/thomas/.virtualenvs/blueprint-app/lib/python3.12/site-packages/environ/compat.py", line 14, in <module>
    if find_loader('simplejson'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/.pyenv/versions/3.12.2/lib/python3.12/pkgutil.py", line 301, in find_loader
    warnings._deprecated("pkgutil.find_loader",
  File "/Users/thomas/.pyenv/versions/3.12.2/lib/python3.12/warnings.py", line 530, in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
```

**Comment by graingert-coef** [comment]
fixed by https://github.com/joke2k/django-environ/pull/482
