### ISSUE TITLE
Cache url for redis provide wrong LOCATION params.

### ISSUE THREAD

**Issue by aldarund** [joke2k/django-environ#62]
I have following env var.
CACHE_URL=rediscache://broker:6379
Which is expanded by environ to following:
{'default': {'BACKEND': 'django_redis.cache.RedisCache',
  'LOCATION': 'broker:6379'}}

But its incorrect. 
django redis  will give following error with this:
ConnectionError: Error 111 connecting to None:6379. Connection refused.

And if we look into django redis docks we will see following:
http://niwinz.github.io/django-redis/latest/

This is a examples of url format
redis://[:password]@localhost:6379/0
rediss://[:password]@localhost:6379/0
unix://[:password]@/path/to/socket.sock?db=0

And as you see scheme is needed. But environ dont pass scheme into location, so redis cache fails to work.

Im not sure for earlier version of django-redis, but current works like i described.

**Comment by joke2k** [comment]
I'm preparing a PR for fix redis support at #61 
Probably we can fix just for the first two url formats, for the third one, `unix://` i can't detect which cache system is used.

**Comment by joke2k** [comment]
Ok the branch is ready.
Can you test if it works?

https://github.com/joke2k/django-environ/tree/redis-support

**Comment by aldarund** [comment]
Not working.
Here is stacktrace if i just launch project that was working on master( although without redis cache).
Now it just produce error on start.
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/rentapplication/django-rentapplication/rentapplication/__init__.py", line 1, in <module>
    from .celery import celery_app
  File "/home/rentapplication/django-rentapplication/rentapplication/celery.py", line 8, in <module>
    import environ
  File "/src/django-environ/environ/__init__.py", line 1, in <module>
    from .environ import *
  File "/src/django-environ/environ/environ.py", line 40, in <module>
    import redis_cache
  File "/usr/local/lib/python2.7/dist-packages/redis_cache/__init__.py", line 1, in <module>
    from redis_cache.cache import RedisCache
  File "/usr/local/lib/python2.7/dist-packages/redis_cache/cache.py", line 1, in <module>
    from django.core.cache.backends.base import BaseCache, InvalidCacheBackendError
  File "/usr/local/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/rentapplication/django-rentapplication/rentapplication/settings.py", line 18, in <module>
    env = environ.Env()
AttributeError: 'module' object has no attribute 'Env'
```
And if i just launch python console and try to import environ following error:
```
>>> import environ
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/src/django-environ/environ/__init__.py", line 1, in <module>
    from .environ import *
  File "/src/django-environ/environ/environ.py", line 40, in <module>
    import redis_cache
  File "/usr/local/lib/python2.7/dist-packages/redis_cache/__init__.py", line 1, in <module>
    from redis_cache.cache import RedisCache
  File "/usr/local/lib/python2.7/dist-packages/redis_cache/cache.py", line 1, in <module>
    from django.core.cache.backends.base import BaseCache, InvalidCacheBackendError
  File "/usr/local/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by joke2k** [comment]
Can you try again?

**Comment by aldarund** [comment]
now it works for me

**Comment by joke2k** [comment]
Ok, Ill'merge soon
