### ISSUE TITLE
ImproperlyConfigured exception when running django-admin.py flush

### ISSUE THREAD

**Issue by jordanmkoncz** [joke2k/django-environ#78]
When running the command `django-admin.py flush` I get the following error:

```
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

In `project_directory/settings.py` I have:

```
USE_I18N = True
DATABASES = { 'default': env.db()}
```

In `root_directory/.env` I have:

```
DATABASE_URL=postgresql://postgres_user:postgres_password@localhost:5432/postgres_database
```

I can run other `django-admin.py` commands without any issues (e.g. `django-admin.py startapp test_app`), and I can also run `manage.py` commands without any issues (e.g. `python manage.py createsuperuser`). It seems to be only the `django-admin.py flush` command that doesn't work.

Here is the full stacktrace:

```
Traceback (most recent call last):
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/core/management/base.py", line 391, in execute
    saved_locale = translation.get_language()
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/utils/translation/__init__.py", line 176, in get_language
    return _trans.get_language()
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dev/django-project/venv/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/core/management/base.py", line 360, in run_from_argv
    connections.close_all()
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/db/utils.py", line 230, in close_all
    for alias in self:
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/db/utils.py", line 224, in __iter__
    return iter(self.databases)
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/db/utils.py", line 157, in databases
    self._databases = settings.DATABASES
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/dev/django-project/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

In case it's relevant, here is my `wsgi.py` file:

```
import os

from django.core.wsgi import get_wsgi_application
from dj_static import Cling, MediaCling

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")

application = Cling(MediaCling(get_wsgi_application()))
```

**Comment by jordanmkoncz** [comment]
There is a closed issue (https://github.com/joke2k/django-environ/issues/76) that seems to be a similar problem to mine, so I tried the solution from this issue of moving `root_directory/.env` to `project_directory.env` and updating my `project_directory/settings.py` accordingly to load the `.env` file from the new location. Unfortunately this didn't seem to have any effect.

**Comment by jordanmkoncz** [comment]
After further research it seems like this problem probably has nothing to do with django-environ and is an issue with PyCharm's environment variables not working correctly for whatever reason, causing `django-admin.py` to not know what settings module to use.

I got around the issue by just doing `python manage.py flush` instead.

**Comment by mehdimortaz** [comment]
its happen to me too , i just now found unintentional i changed "configuration" in top of PyCharm IDE so pycharm confused when try to run django code. exactly the problem popup when i try to runserver with shortcut but when i used terminal to runserver i found django code havent any problem and pycharm cant found setting. so plz check "configuration" in top pycharm's ide maybe u do same mistake :)
im new in django so be calm if my answer was silly.
![problem](https://user-images.githubusercontent.com/45900756/54115518-d7f00c00-4401-11e9-9d2f-5e339c8ef66b.PNG)
.
