### ISSUE TITLE
tests fail with Python 3.5

### ISSUE THREAD

**Issue by brianmay** [joke2k/django-environ#84]
```
======================================================================
ERROR: test_bool_false (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_bool_true (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_cache_url_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_db_url_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_dict_parsing (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_dict_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_email_url_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_empty_list (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_float (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_int (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_int_list (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_int_tuple (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_int_with_none_default (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_json_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_not_present_with_default (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_not_present_without_default (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_path (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_proxied_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_str (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_str_list_with_spaces (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

======================================================================
ERROR: test_url_value (environ.test.FileEnvTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/environ/test.py", line 213, in setUp
    self.env.read_env(file_path, PATH_VAR=Path(__file__, is_file=True).__root__)
  File "/<<PKGBUILDDIR>>/environ/environ.py", line 577, in read_env
    content = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 960: ordinal not in range(128)

----------------------------------------------------------------------
Ran 76 tests in 0.019s

FAILED (errors=21)
```

**Comment by brianmay** [comment]
Looks like the problem is from ./environ/test_env.txt:

```
CYRILLIC_VAR=фуубар
```

The ф character is non-ascii.

Later: Oh. I see. To run the tests we have to select a UTF8 locale in LANG first. e.g. C.UTF-8 works fine.

I am undecided if this is a bug or or not. If you feel it isn't a bug, suggest you document this requirement somewhere and close the bug.

**Comment by Duologic** [comment]
I have a similar issue with an UTF-8 character in my environment.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<snip>/venv/lib/python2.7/site-packages/environ/environ.py", line 117, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/<snip>/venv/lib/python2.7/site-packages/environ/environ.py", line 255, in get_value
    if hasattr(value, 'startswith') and value.startswith('$'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)
'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)
```

We could do something like this:
```
    def get_value(self, var, cast=None, default=NOTSET, parse_default=False, encoding='ascii'):
        ...
        try:
            value = unicode(self.ENVIRON[var], encoding)
        except KeyError:
            if default is self.NOTSET:
                error_msg = "Set the {0} environment variable".format(var)
                raise ImproperlyConfigured(error_msg)
        ...
        return value
```

This should work on Python 2.7, not sure how this all goes for other Python versions.

Currently I avoid django-environ where I think UTF-8 chars will pop up and simply do this: `unicode(os.environ[var], 'utf8')`

**Comment by brianmay** [comment]
@Duologic My understanding is that this shouldn't be a problem if your locale is configured correctly. If you want to put UTF8 in your environment you really should have a UTF8 locale selected.

e.g.

```
brian@prune:~$ export LANG=en_AU.UTF-8
brian@prune:~$ locale
LANG=en_AU.UTF-8
LANGUAGE=
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
```

My bug report was specifically referring to the tests, and that it is somewhat unusual to have to select a UTF8 local in order to run the tests. IIRC this isn't documented anywhere.

**Comment by Duologic** [comment]
I'll create a new issue to discuss my case then.

**Comment by sergeyklay** [comment]
Python 3.5 no longer supported. I'm sorry for the delay.
